@startuml C4-Container-Marketplace
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title C4 Container - Marketplace

Person(buyer, "Покупатель")
Person(seller, "Продавец")

System_Boundary(mp, "Marketplace") {

    Container(web, "Web / приложение", "React / Mobile", "")
    Container(gw, "API Gateway", "FastAPI", "")

    Container(identity, "Identity", "", "")
    Container(catalog, "Catalog", "", "")
    Container(feed, "Search and Feed", "", "")
    Container(order, "Ordering", "", "")
    Container(payment, "Payments", "", "")
    Container(notify, "Notifications", "", "")

}

System_Ext(psp, "Payment provider")
System_Ext(ch, "Email / Push / SMS")

Rel(buyer, web, "HTTPS")
Rel(seller, web, "HTTPS")
Rel(web, gw, "REST")

Rel(gw, identity, "REST")
Rel(gw, catalog, "REST")
Rel(gw, feed, "REST")
Rel(gw, order, "REST")
Rel(gw, payment, "REST")
Rel(gw, notify, "REST")

Rel(order, catalog, "REST")
Rel(catalog, feed, "REST")
Rel(order, notify, "REST")
Rel(payment, notify, "REST")

Rel(payment, psp, "HTTPS")
Rel(notify, ch, "HTTPS")

@enduml
