@startuml C4-Context-Marketplace
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title C4 Context - Marketplace

Person(buyer, "Покупатель")
Person(seller, "Продавец")

System(marketplace, "Marketplace", "магазин")

System_Ext(psp, "Payment provider")
System_Ext(ext, "уведомления, KYC", "")

Rel(buyer, marketplace, "HTTPS")
Rel(seller, marketplace, "HTTPS")
Rel(marketplace, psp, "REST")
Rel(marketplace, ext, "API")

@enduml
