@startuml C4-Container-Marketplace
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title C4 Container - Marketplace

Person(buyer, "Покупатель")
Person(seller, "Продавец")

System_Boundary(mp, "Marketplace") {

    Container(web, "Web / приложение", "React / Mobile", "")
    Container(gw, "API Gateway", "FastAPI", "точка входа")

    Container(identity, "Identity", "", "")
    Container(catalog, "Catalog", "", "")
    Container(feed, "Search and Feed", "", "")
    Container(order, "Ordering", "", "")
    Container(payment, "Payments", "", "")
    Container(notify, "Notifications", "", "")

    ContainerQueue(bus, "Kafka", "", "")
}

System_Ext(psp, "Payment provider")
System_Ext(ch, "Email / Push / SMS")

Rel(buyer, web, "HTTPS")
Rel(seller, web, "HTTPS")
Rel(web, gw, "REST")

Rel(gw, identity, "")
Rel(gw, catalog, "")
Rel(gw, feed, "")
Rel(gw, order, "")
Rel(gw, payment, "")

Rel(catalog, bus, "")
Rel(order, bus, "")
Rel(identity, bus, "")
Rel(payment, bus, "")
Rel(bus, feed, "")
Rel(bus, notify, "")

Rel(order, catalog, "")
Rel(payment, psp, "")
Rel(notify, ch, "")

@enduml
